In [3]:
import numpy as np

A = np.array([[4,7,8] , [-9,0,0], [2,3,4]])

print(A)

round(np.linalg.det(A))

[[ 4  7  8]
 [-9  0  0]
 [ 2  3  4]]


36

In [6]:
import numpy as np

A = np.array([[1,2,-1] , [4,6,-2], [-1,3,3]])

print(A)

round(np.linalg.det(A))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]


-14