Problem 1

In [ ]:
# Given
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[1, 2],
              [3, 4],
              [5, 6]])
C = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
D = np.array([[1, 2],
              [3, 4]])

In [3]:
#a.

AB = np.dot(A, B)
print("Answer: ")
print(AB)

Answer: 
[[22 28]
 [49 64]]


In [5]:
#b.

DPD = D + D
print("\nAnswer: ")
print(DPD)


Answer: 
[[2 4]
 [6 8]]


In [6]:
#c.

tuk = 2 * C
print("\nAnswer: ")
print(tuk)


Answer: 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Problem 2

In [9]:
#Cross Product

A = np.array([2, 7, 4])
B = np.array([3, 9, 8])
R = np.cross(A, B)

print("Answer: ")
print(R)

Answer: 
[20 -4 -3]
