Vector

In [5]:
import numpy as np

A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


Matrix

In [24]:
import numpy as np

###Checking Shapes
###Shapes tells us how many rows and columns are there

ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

###ball = pool.npshape

print(ball1)
print(ball2)

ball = np.shape([[ball1] , [ball2]])
print(ball)

[1 2 3]
[ 0  1 -1]
(2, 1, 3)


Vector Operations

In [34]:
import numpy as np
#Addition

A = np.array([4, 3])
B = np.array([2, -5])
R = np.add(A, B)

print(R)

[ 6 -2]


In [35]:
#Subtraction
import numpy as np


A = np.array([4, 3])
B = np.array([2, -5])
R = np.subtract(A, B)

print(R)

[2 8]


In [37]:
#Scalar Product

S = np.array([2])
V = S*A

print(V)

[8 6]


In [47]:
#Dot Product

A = np.array([4, 3])
B = np.array([[2], [-5]])
R = A * B

print(R)

[[  8   6]
 [-20 -15]]


Property of Matrix

In [57]:
#Identity Matrix

c = np.eye(6,6)

print(c)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [65]:
#Zero Matrix

d = np.zeros([9,9])

print(d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [74]:
#Full Matrix

e = np.full([3,3], 11)

print(e)

[[11 11 11]
 [11 11 11]
 [11 11 11]]


In [75]:
#Transpose Matrix

f = np.transpose(e)

print(f)

[[11 11 11]
 [11 11 11]
 [11 11 11]]
