Question 1.

In [10]:
import numpy as np

def multiChart(n):
    range = np.arange(1, n+1)
    return range * range[:, None]

print("Output array: \n\n",multiChart(10))

Output array: 

 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


Question 2.

In [3]:
import numpy as np

def multiChart(n):
    range = np.arange(1, n+1)
    return range * range[:, None]

print(multiChart(10) * 2)

[[  2   4   6   8  10  12  14  16  18  20]
 [  4   8  12  16  20  24  28  32  36  40]
 [  6  12  18  24  30  36  42  48  54  60]
 [  8  16  24  32  40  48  56  64  72  80]
 [ 10  20  30  40  50  60  70  80  90 100]
 [ 12  24  36  48  60  72  84  96 108 120]
 [ 14  28  42  56  70  84  98 112 126 140]
 [ 16  32  48  64  80  96 112 128 144 160]
 [ 18  36  54  72  90 108 126 144 162 180]
 [ 20  40  60  80 100 120 140 160 180 200]]


Question 3

In [5]:
import numpy as np

skwer = np.eye(5,5)

print(skwer)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Question 4.


In [11]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("Given matrix: \n", matrix)

size = np.size([[matrix]])
shape = np.shape([matrix])
print("\nsize of the matrix: ", size)
print("\nshape and dimension of the matrix: ", shape)

Given matrix: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

size of the matrix:  12

shape and dimension of the matrix:  (1, 3, 4)


Question 5.

In [19]:
import numpy as np

arrayOne = np.array([[5,6,9], [21,18,27]])
arrayTwo = np.array([[15,33,24], [4,7,1]])

R = arrayOne + arrayTwo
print("The sum of the arrays: \n", R)

Z = (R * R)
print("\n The square of the resultant: \n", Z)

The sum of the arrays: 
 [[20 39 33]
 [25 25 28]]

 The square of the resultant: 
 [[ 400 1521 1089]
 [ 625  625  784]]
