In [7]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

G = np.array([
    [1,1],
    [2,2]
])
describe_mat(G)


Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2



In [6]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)


Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [4]:
H = np.array([1,2,3,4,5])
describe_mat(H)


Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1

